
services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=bookstore_db
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d bookstore_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - backend
    # depends_on:
    #   - db
    depends_on:
    db:
      condition: service_healthy

networks:
  backend: 
    driver: bridge

volumes:
  postgres_data: