name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: bookstore_db
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U dev -d bookstore_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry

    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
      run: | 
        python -m poetry lock
        python -m poetry install

    - name: Run migrations
      env:
        DATABASE_URL: postgresql://dev:dev@localhost:5432/bookstore_db
      run: | 
        sleep 10
        poetry run python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgresql://dev:dev@localhost:5432/bookstore_db
      run: |
        poetry run python manage.py test
